kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph # namespace:cluster
data:
  config: |
    [global]
    public network =  33.33.33.0/24
    cluster network = 44.44.44.0/24
    public addr = ""
    cluster addr = ""
    #
    #osd_pool_default_size = 1
    #mon_warn_on_pool_no_redundancy = false
