kind: ServiceAccount
apiVersion: v1
metadata:
  name: ceph-root
  namespace: rook-ceph
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ceph-cluster-admin-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: ceph-root
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
